### ISSUE TITLE
Run React server

### ISSUE THREAD

**Issue by doorooful** [doorooful/CapstoneProject#103]
AC:
- Run react server on the local PC
- Update `dt-demo-fe/README.md` if needed
- If there's no code updates: Paste screenshot on comment - PR not needed
- If there's code updates: Create PR

**Comment by leeinsunny** [comment]
I finshed run react server. And there are no updating of README.md
![image](https://github.com/doorooful/CapstoneProject/assets/105425832/918ab348-261a-44ee-976d-627cd381bb5b)

**Comment by doorooful** [comment]
Great!!
