### ISSUE TITLE
Environment setup

### ISSUE THREAD

**Issue by doorooful** [doorooful/CapstoneProject#107]
AC:
- Download ubuntu22.04 on your computer
- Create fork from this repo
- Clone repo on your wsl env

**Comment by OSsunNO** [comment]
environment setting complete
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/fa2f06c4-9681-4849-aa03-ea7f4fa7799d)

**Comment by doorooful** [comment]
Great!
