### ISSUE TITLE
Run react server

### ISSUE THREAD

**Issue by doorooful** [doorooful/CapstoneProject#108]
AC:
- Install nodejs >= 14.0
- Install necessary npm packages according to `CapstoneProject/dt-demo-fe/README.md`
- Verify if `npm start` command works

**Comment by OSsunNO** [comment]
- Install nodejs >= 14.0
   1. Install nodejs & npm by following installation instructions in https://github.com/nodesource/distributions
   
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/7b8eb1ea-8314-4ba6-81ca-85193872386c)

      1-1) Result
      
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/5076a820-494e-4769-a747-04a25a0cdf62)

**Comment by OSsunNO** [comment]
- Install necessary npm packages according to CapstoneProject/dt-demo-fe/README.md
   1. Result
      
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/b8372846-5117-4d82-a3f5-445bc7c258d3)

**Comment by OSsunNO** [comment]
- Verify if npm start command works
   1. Result
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/fe98a7d0-abd5-4675-97a6-ad9523785a93)
