### ISSUE TITLE
Run flask server

### ISSUE THREAD

**Issue by doorooful** [doorooful/CapstoneProject#109]
AC:
- Create virtual environment under `CapstoneProject` folder with python version>=3.9 ( i.e. `python3 -m venv .venv`)
- Activate virtual environment (i.e. `source .venv/bin/activate`)
- Install pip packages(`CapstoneProject/dt-demo-be/README.md` file doesn't have sufficient information, Please ask @leeinsunny for the necessary packages)
- Run Flask api under `dt-demo-be`

- Verify Flask api works with Postman: 
- Download from here! https://www.postman.com/downloads/

**Comment by OSsunNO** [comment]
1. python-venv package is needed to make python virtual environment in the Ubuntu environment
   - $ sudo apt install python3.10-venv
2. Create virtual environment
   - $ python3 -m venv .venv
3. Activate virtual environment
   - $ source .venv/bin/activate
 
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/440cfae4-59db-475e-b798-674b134e8b02)

4. Intall pip packages
   - sudo apt install python3-pip
   - pip install flask
   - pip install falsk-cors
   - pip install requests
   - pip install pandas
5. Run flask api under dt-demo-be
   - /dt-demo-be $ FLASK_APP = app.py flask run
6. Verify Flask api works with Postman
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/e76d9dd8-2cfb-444b-9530-933c0dcf1265)

**Comment by doorooful** [comment]
Can you update `dt-demo-be/README.md` regarding your practice?
