### ISSUE TITLE
Typo API

### ISSUE THREAD

**Issue by yoouung** [doorooful/CapstoneProject#24]

**Comment by yoouung** [comment]
https://console.kakaoi.io/docs/posts/aiservice-nlp/kgc/2022-05-26-aiservice-kgc_howto/aiservice-kgc_howto#%EB%A7%9E%EC%B6%A4%EB%B2%95-%EA%B2%80%EC%82%AC-%EC%82%AC%EC%9A%A9-%EA%B0%80%EC%9D%B4%EB%93%9C

기업용 카카오 클라우드 -> 카카오 맞춤법 검사기 api 사용 가능

**Comment by doorooful** [comment]
Please try py-hanspell on python 3.4

**Comment by doorooful** [comment]
New reference: https://hleecaster.com/speller-cs-pusan-ac-kr/
