### ISSUE TITLE
Update Slang module by appending more words on dictionary

### ISSUE THREAD

**Issue by yoouung** [doorooful/CapstoneProject#65]
AC:
Add more slang words on dictionary, and test

**Comment by yoouung** [comment]
[wordchk_search.js.zip](https://github.com/doorooful/CapstoneProject/files/12435691/wordchk_search.js.zip)

**Comment by doorooful** [comment]
Here is the updated version of dictionary file.

[slang_dict.xlsx](https://github.com/doorooful/CapstoneProject/files/12435832/slang_dict.xlsx)
